# Generated by Django 5.0.6 on 2025-01-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internalId', models.IntegerField()),
                ('documentNumber', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
